repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    # - id: go-cyclo
    #   args: [-over=25]
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    # - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy