# https://taskfile.dev
version: '3'
vars:
  BINFILE: gocrypt

includes:
  dev: ./Taskfile_dev.yml

tasks:

  default:
    desc: "List tasks"
    cmds:
      - task -a

  lint:
    desc: "Run linter"
    cmds:
      - golangci-lint run
  

  binary:
    desc: "Build binary"
    cmds:
      - CGO_ENABLED=0 go build -o gocrypt cmd/*.go
    # silent: true

  tests:
    desc: "Run tests"
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure
      - venom run ts-envvar.yml --output-dir="log" --stop-on-failure
      - venom run TS-bigfile.yml --output-dir="log" --stop-on-failure

  snapshot:
    desc: "Create snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate
    