# https://taskfile.dev
version: '3'
vars:
  BINFILE: gocrypt

tasks:
  default:
    cmds:
      #- echo "{{.GREETING}}"
      - CGO_ENABLED=0 go build .
      - upx -q {{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  hook-prereq:
    cmds:
      - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - go install -v github.com/go-critic/go-critic/cmd/gocritic@latest

  pre-commit:
    cmds:
      - pre-commit

  tests:
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure
      - venom run TS-bigfile.yml --output-dir="log" --stop-on-failure

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist
    