# https://taskfile.dev
version: '3'
vars:
  BINFILE: gocrypt

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    cmds:
      - CGO_ENABLED=0 go build .
      - upx -q {{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  tests:
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure
      - venom run TS-bigfile.yml --output-dir="log" --stop-on-failure

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
    